Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,6 +20,10 @@ jobs:
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-south-1
 
+    - name: Verify Docker Login
+      run: |
+        docker info
+
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1
@@ -28,7 +32,7 @@ jobs:
       id: build-image
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-        ECR_REPOSITORY: techdome-application-frontend  # Corrected repository name
+        ECR_REPOSITORY: techdome-application-frontend
         IMAGE_TAG: v1
       
       run: |
@@ -43,8 +47,13 @@ jobs:
           echo "Docker images after build:"
           docker images $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
-          echo "step:2 Pushing Frontend image to ECR..."
-          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  # Corrected push command
-  
-          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+          echo "Step:2 Pushing Frontend image to ECR..."
+          echo "Docker images before push:"
+          docker images
 
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || (echo "Docker push failed"; exit 1)
+
+          echo "Docker images after push:"
+          docker images
+
+          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
